/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{astro,html,js,jsx,ts,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#d3ceef",
        "on-secondary-fixed-variant": "#4e5c71",
        "secondary-fixed": "#d5e3fc",
        "primary-dim": "#5d74d1",
        "primary-container": "#eef1ff",
        "secondary-dim": "#465468",
        "on-primary-fixed": "#253b9f",
        "background": "#f7f9fb",
        "surface-tint": "#788FEC",
        "surface-bright": "#f7f9fb",
        "secondary-fixed-dim": "#c7d5ed",
        "on-secondary-fixed": "#324053",
        "outline-variant": "#a9b4b9",
        "on-tertiary": "#fcf7ff",
        "on-surface": "#2a3439",
        "on-background": "#2a3439",
        "tertiary-container": "#d3ceef",
        "primary-fixed": "#e0e4ff",
        "error-dim": "#4e0309",
        "outline": "#717c82",
        "surface-container-high": "#e1e9ee",
        "error-container": "#fe8983",
        "surface-container-lowest": "#ffffff",
        "on-error": "#fff7f6",
        "on-secondary-container": "#455367",
        "on-primary": "#f7f7ff",
        "on-error-container": "#752121",
        "secondary": "#526074",
        "surface-container": "#e8eff3",
        "on-tertiary-container": "#47445f",
        "on-primary-container": "#3f54b8",
        "surface-variant": "#d9e4ea",
        "primary": "#788FEC",
        "inverse-on-surface": "#9a9d9f",
        "on-surface-variant": "#566166",
        "tertiary-dim": "#53506b",
        "error": "#9f403d",
        "on-secondary": "#f8f8ff",
        "surface-dim": "#cfdce3",
        "inverse-surface": "#0b0f10",
        "surface-container-highest": "#d9e4ea",
        "surface-container-low": "#f0f4f7",
        "tertiary-fixed-dim": "#c5c0e0",
        "secondary-container": "#d5e3fc",
        "on-primary-fixed-variant": "#4f66cc",
        "inverse-primary": "#b0bdff",
        "surface": "#f7f9fb",
        "primary-fixed-dim": "#c8cfff",
        "on-tertiary-fixed-variant": "#504e69",
        "tertiary": "#5f5c78",
        "on-tertiary-fixed": "#34314b"
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [],
};
